// import { products } from '../../products.js';
export const products = [
    {
      id: 1,
      title: "Chocolate Kit-Kat 100g 70% Cocoa",
      image: "https://docemalu.vtexassets.com/arquivos/ids/5357847/125561-2.jpg?v=638669347365970000",
      nutritionalValues: {
        kcal: 500,
        carboidrato: 46,
        proteina: 5.6,
        totalGordura: 28.8,
        saturadaGordura: 14,
        fibra: 5.5,
        sodio: 0.04,
        acucar: 44.8,
      },
    },
    {
      id: 2,
      title: "Chocolate Milka 100g Extra Cocoa",
      image: "https://d21wiczbqxib04.cloudfront.net/XhZ6OeJF8YexRqKNoV2O1QcOAAM=/1600x0/smart/https://produtos-osuper.s3.amazonaws.com/26204.jpg",
      nutritionalValues: {
        kcal: 551,
        carboidrato: 46,
        proteina: 7.6,
        totalGordura: 36,
        saturadaGordura: 22,
        fibra: 5.8,
        sodio: 0.24,
        acucar: 43,
      },
    },
    {
        id: 3,
        title: "Pão de Forma Pullman",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 265,
          carboidrato: 45,
          proteina: 8,
          totalGordura: 4.2,
          saturadaGordura: 1.2,
          fibra: 1.3,
          sodio: 0.6,
          acucar: 3.1,
        },
      },
      {
        id: 4,
        title: "Leite Longa Vida Itambé 1L",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 66,
          carboidrato: 5.2,
          proteina: 3.2,
          totalGordura: 3.5,
          saturadaGordura: 2.2,
          fibra: 0,
          sodio: 0.05,
          acucar: 5.2,
        },
      },
      {
        id: 5,
        title: "Macarrão Espaguete Barilla 500g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 350,
          carboidrato: 70,
          proteina: 12,
          totalGordura: 1.5,
          saturadaGordura: 0.5,
          fibra: 3,
          sodio: 0.01,
          acucar: 1.5,
        },
      },
      {
        id: 6,
        title: "Molho de Tomate Elefante 340g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 90,
          carboidrato: 19,
          proteina: 3,
          totalGordura: 0.5,
          saturadaGordura: 0.05,
          fibra: 2.5,
          sodio: 0.6,
          acucar: 8,
        },
      },
      {
        id: 7,
        title: "Arroz Tio João 1kg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 365,
          carboidrato: 80,
          proteina: 6.8,
          totalGordura: 0.8,
          saturadaGordura: 0.2,
          fibra: 1.4,
          sodio: 0.005,
          acucar: 0,
        },
      },
      {
        id: 8,
        title: "Feijão Carioca Camil 1kg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 345,
          carboidrato: 62.5,
          proteina: 21,
          totalGordura: 1.2,
          saturadaGordura: 0.2,
          fibra: 8.6,
          sodio: 0.003,
          acucar: 0.4,
        },
      },
      {
        id: 9,
        title: "Café Melitta 500g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 175,
          carboidrato: 0.2,
          proteina: 0.1,
          totalGordura: 0.1,
          saturadaGordura: 0.0,
          fibra: 0,
          sodio: 0,
          acucar: 0,
        },
      },
      {
        id: 10,
        title: "Açúcar União 1kg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 387,
          carboidrato: 98,
          proteina: 0,
          totalGordura: 0,
          saturadaGordura: 0,
          fibra: 0,
          sodio: 0,
          acucar: 97.5,
        },
      },
      {
        id: 11,
        title: "Sal Refinado Cisne 1kg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 0,
          carboidrato: 0,
          proteina: 0,
          totalGordura: 0,
          saturadaGordura: 0,
          fibra: 0,
          sodio: 380,
          acucar: 0,
        },
      },
      {
        id: 12,
        title: "Cereal Matinal Kellogg's 500g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 200,
          carboidrato: 50,
          proteina: 5,
          totalGordura: 1.5,
          saturadaGordura: 0.2,
          fibra: 4.2,
          sodio: 0.1,
          acucar: 12,
        },
      },
      {
        id: 13,
        title: "Suco Del Valle Laranja 1L",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 45,
          carboidrato: 11.5,
          proteina: 0.5,
          totalGordura: 0,
          saturadaGordura: 0,
          fibra: 0.5,
          sodio: 0.01,
          acucar: 10.5,
        },
      },
      {
        id: 14,
        title: "Óleo de Soja Liza 900ml",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 810,
          carboidrato: 0,
          proteina: 0,
          totalGordura: 90,
          saturadaGordura: 10,
          fibra: 0,
          sodio: 0,
          acucar: 0,
        },
      },
      {
        id: 15,
        title: "Margarina Qualy 500g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 700,
          carboidrato: 0.4,
          proteina: 0.6,
          totalGordura: 78,
          saturadaGordura: 16,
          fibra: 0,
          sodio: 0.35,
          acucar: 0.2,
        },
      },
      {
        id: 16,
        title: "Queijo Prato Polenghi 200g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 320,
          carboidrato: 2.5,
          proteina: 18,
          totalGordura: 25,
          saturadaGordura: 15,
          fibra: 0,
          sodio: 0.7,
          acucar: 2,
        },
      },
      {
        id: 17,
        title: "Presunto Sadia 200g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 300,
          carboidrato: 2,
          proteina: 18,
          totalGordura: 24,
          saturadaGordura: 8,
          fibra: 0,
          sodio: 1.3,
          acucar: 0.2,
        },
      },
      {
        id: 18,
        title: "Frango Congelado Perdigão 1kg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 210,
          carboidrato: 0,
          proteina: 20,
          totalGordura: 14,
          saturadaGordura: 3.5,
          fibra: 0,
          sodio: 0.1,
          acucar: 0,
        },
      },
      {
        id: 19,
        title: "Linguiça Calabresa Perdigão 500g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 320,
          carboidrato: 2,
          proteina: 12,
          totalGordura: 28,
          saturadaGordura: 12,
          fibra: 0,
          sodio: 1.8,
          acucar: 0,
        },
      },
      {
        id: 20,
        title: "Batata Congelada McCain 1kg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 160,
          carboidrato: 37,
          proteina: 2,
          totalGordura: 0.5,
          saturadaGordura: 0.1,
          fibra: 5,
          sodio: 0.05,
          acucar: 0,
        },
      },
      {
        id: 21,
        title: "Refrigerante Coca-Cola 2L",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 180,
          carboidrato: 45,
          proteina: 0,
          totalGordura: 0,
          saturadaGordura: 0,
          fibra: 0,
          sodio: 0.01,
          acucar: 40,
        },
      },
      {
        id: 22,
        title: "Suco de Uva Integral Aurora 1L",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 150,
          carboidrato: 38,
          proteina: 0.7,
          totalGordura: 0.5,
          saturadaGordura: 0.1,
          fibra: 0.5,
          sodio: 0.01,
          acucar: 35,
        },
      },
      {
        id: 23,
        title: "Yogurte Grego Danone 400g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 120,
          carboidrato: 9,
          proteina: 10,
          totalGordura: 7,
          saturadaGordura: 5,
          fibra: 0,
          sodio: 0.1,
          acucar: 5,
        },
      },
      {
        id: 24,
        title: "Biscoito Trakinas 400g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 520,
          carboidrato: 65,
          proteina: 6,
          totalGordura: 27,
          saturadaGordura: 15,
          fibra: 1.5,
          sodio: 0.4,
          acucar: 30,
        },
      },
      {
        id: 25,
        title: "Amendoim Japonês 400g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 570,
          carboidrato: 28,
          proteina: 18,
          totalGordura: 50,
          saturadaGordura: 9,
          fibra: 8,
          sodio: 0.3,
          acucar: 2,
        },
      },
      {
        id: 26,
        title: "Suco de Laranja Natural Sufresh 1L",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 40,
          carboidrato: 10,
          proteina: 0.3,
          totalGordura: 0,
          saturadaGordura: 0,
          fibra: 0.2,
          sodio: 0.01,
          acucar: 9.5,
        },
      },
      {
        id: 27,
        title: "Biscoito Oreo 154g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 500,
          carboidrato: 70,
          proteina: 5,
          totalGordura: 25,
          saturadaGordura: 5,
          fibra: 1,
          sodio: 0.1,
          acucar: 40,
        },
      },
      {
        id: 28,
        title: "Manteiga Aviação 500g",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpZaeWxczipxrTdSIThz5hmwrRYhEeeAl5A&s",
        nutritionalValues: {
          kcal: 710,
          carboidrato: 0.1,
          proteina: 1,
          totalGordura: 82,
          saturadaGordura: 52,
          fibra: 0,
          sodio: 0.02,
          acucar: 0,
        },
      },
      
    ];
